services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  develop:
    container_name: neuralcam-develop
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    profiles: [ develop ]
    volumes:
      - $PWD:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.cache/pip:/root/.cache/pip
    build:
      dockerfile: Dockerfile.develop
      context: .
    network_mode: host
    #  watch:
    #    - action: rebuild
    #      path: .
  mongo-express:
    container_name: neuralcam-mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8090:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=testDB
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=toor
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=example
  mongo:
    container_name: neuralcam-mongo
    image: mongo:7.0.21
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - neuralcam-mongo:/data/db

volumes:
  neuralcam-mongo:
